# Generated by Django 4.2.7 on 2023-11-08 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testpages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='results',
            name='test_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='testpages.testpages'),
        ),
        migrations.AddField(
            model_name='questions',
            name='page_headline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpages.testpages'),
        ),
        migrations.AddField(
            model_name='options',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testpages.questions'),
        ),
    ]
